### ISSUE TITLE
Add more text for WebGL use cases

### ISSUE THREAD

**Issue by kenrussell** [dalecurtis/video-animation-frame#1]
The WebGL use cases, and interaction with the WEBGL_video_texture extension, should be filled out more in this explainer.

**Comment by kenrussell** [comment]
CC @kainino0x @shaoboyan .

Related to https://github.com/KhronosGroup/WebGL/issues/2897 .

**Comment by dalecurtis** [comment]
I was thinking something along the lines of WebGL clients would like to composite at the video rate and not the refresh rate to save on processing expense. This would also allow replacement of any polling based solution.

**Comment by kenrussell** [comment]
Sounds good.
