### ISSUE TITLE
Clarify when `presentationTimestamp` will be missing

### ISSUE THREAD

**Issue by Yay295** [dalecurtis/video-animation-frame#4]
Currently the documentation for `presentationTimestamp` says:
> The presentation timestamp in seconds of the frame presented. May not be known to the compositor or exist in all cases.

For a use case I have in mind, the `presentationTimestamp` is the field I care about the most (in fact, it's the only field I care about). I would like it to specified under which circumstances this field would not exist as it directly impacts the usefulness of this method to me.

**Comment by tguilbert-google** [comment]
In the WebRTC case, we may not always have a presentationTimestamp. For normal media playback, we should always have a PTS.
